import json
D=[]
def d(id,name,group,role,start=None,target=None,summary="",points=(),cautions=(),terms=(),pages="",note=None):
    D.append(dict(id=id,name=name,group=group,role=role,start=start,target=target,summary=summary,points=list(points),cautions=list(cautions),terms=list(terms),pages=pages,note=note))
ACE="ACE inhibitors"
aceS="First class of drugs shown to reduce mortality and morbidity and improve symptoms in HFrEF; recommended in all patients with HFrEF unless contraindicated or not tolerated, uptitrated to the highest recommended dose (intermediate doses if target not tolerated)."
aceC=["Give with caution if SBP <100 mmHg, eGFR <30 mL/min/1.73 m², or K⁺ >5.2 mEq/L","Avoid abrupt withdrawal (clinical deterioration); if ARNI is not possible, continued ACE-I remains strongly advised","Wash-out of at least 36 h before starting an ARNI (angio-oedema risk)"]
d("captopril","Captopril",ACE,"FMT","6.25 mg t.i.d.","50 mg t.i.d.",aceS,["Target dose derived from post-MI trials"],aceC,["ace-i"],"33, 36")
d("enalapril","Enalapril",ACE,"FMT","2.5 mg b.i.d.","10–20 mg b.i.d.",aceS,["Comparator in PARADIGM-HF (ARNI reduced CV death/HFH by 20% vs enalapril)"],aceC,["ace-i"],"33, 36")
d("lisinopril","Lisinopril",ACE,"FMT","2.5–5 mg o.d.","20–35 mg o.d.",aceS,["Higher dose reduces morbidity/mortality vs lower dose, but no substantive placebo-controlled trial; optimal dose uncertain"],aceC,["ace-i"],"33, 36")
d("ramipril","Ramipril",ACE,"FMT","1.25–2.5 mg b.i.d.","5 mg b.i.d.",aceS,[],aceC,["ace-i"],"33, 36")
d("trandolapril","Trandolapril",ACE,"FMT","0.5 mg o.d.","4 mg o.d.",aceS,["Target dose derived from post-MI trials","PEACE subgroup: mortality reduction in LVEF 40–50%"],aceC,["ace-i"],"33, 36")
d("sacubitril-valsartan","Sacubitril–valsartan (ARNI)","ARNI","FMT","49/51 mg b.i.d.","97/103 mg b.i.d.","Angiotensin receptor–neprilysin inhibitor. In PARADIGM-HF it reduced CV death or HFH by 20% vs enalapril, with better QoL, slower eGFR decline, lower loop-diuretic dose and lower hyperkalaemia risk. Patients tolerating an ACE-I/ARB with persistent symptoms should be switched; may also be used de novo.",["Optional lower start 24/26 mg b.i.d. for history of symptomatic hypotension, ACE-I-naïve patients, or eGFR 30–60 mL/min/1.73 m²","HFpEF: PARAGON-HF missed its primary endpoint; benefit seen with LVEF below ~60–65%, so ARNI may be considered, especially at lower LVEF","Pre- and post-discharge initiation showed similar efficacy/safety with larger NT-proBNP reduction vs ACE-I"],["More frequent symptomatic hypotension","Wash-out ≥36 h after ACE-I","Same caution thresholds as ACE-I (SBP <100, eGFR <30, K⁺ >5.2); avoid abrupt withdrawal","Not recommended in pregnancy"],["arni","acei/arni","ace-i or arni"],"33, 35–36")
ARB="ARBs"
arbS="Recommended in HFrEF for patients who cannot tolerate an ACE-I or ARNI. Much lower incidence of cough and angio-oedema than ACE-I (no kininase inhibition). No ARB has reduced all-cause mortality in any trial; combining with an ACE-I increases adverse effects."
d("candesartan","Candesartan",ARB,"FMT","4 mg o.d.","32 mg o.d.",arbS,["CHARM-Alternative: reduced CV death and HFH in ACE-I-intolerant patients","CHARM-Preserved: primary endpoint neutral; fewer HFH in LVEF 40–49% (retrospective)"],["Evidence limited at higher LVEF"],["arb"],"33, 36")
d("losartan","Losartan",ARB,"FMT","(12.5) 25–50 mg o.d.","150 mg o.d.",arbS,["HEAAL: high-dose losartan reduced HFH vs low dose in ACE-I-intolerant patients"],[],["arb"],"33, 36")
d("valsartan","Valsartan",ARB,"FMT","40 mg b.i.d.","160 mg b.i.d.",arbS,["Val-HeFT: reduced HFH on top of usual therapy including ACE-I"],[],["arb"],"33, 36")
BB="Beta-blockers"
bbS="Reduce morbidity and mortality in HFrEF on top of ACE-I and diuretics. Start early in clinically stable patients at low dose and uptitrate gradually to the highest tolerated dose; continue long-term even if symptoms do not improve."
bbC=["Ensure euvolaemia before initiation","In decompensated HF, initiate cautiously in hospital once haemodynamically stabilized","Effect in HFrEF with AF is uncertain (no dedicated RCT), although useful for rate control","Temporary discontinuation advised in severe haemodynamic instability"]
d("bisoprolol","Bisoprolol",BB,"FMT","1.25 mg o.d.","10 mg o.d.",bbS,["Shown to reduce risk of death in HFrEF","β1-selective: acceptable in pregnancy with HFrEF (switch from non-selective agents)"],bbC,["beta-blocker"],"34, 36")
d("carvedilol","Carvedilol",BB,"FMT","3.125 mg b.i.d.","25 mg b.i.d.",bbS,["Shown to reduce risk of death in HFrEF","Maximum 50 mg b.i.d. may be given to patients >85 kg (Table 11, footnote d)"],bbC,["beta-blocker"],"34, 36")
d("metoprolol","Metoprolol succinate (CR/XL)",BB,"FMT","12.5–25 mg o.d.","200 mg o.d.",bbS,["Sustained-release succinate shown to reduce risk of death in HFrEF","β1-selective: acceptable in pregnancy with HFrEF"],bbC,["beta-blocker"],"34, 36")
d("nebivolol","Nebivolol",BB,"FMT","1.25 mg o.d.","10 mg o.d.",bbS,["Only reduced the combined endpoint of all-cause mortality and CV hospitalization (not shown to reduce CV/all-cause death alone)"],bbC,["beta-blocker"],"34, 36")
MRA="MRAs"
mraS="Recommended in all symptomatic HF regardless of LVEF (steroidal MRA for HFrEF; steroidal or non-steroidal MRA for HFpEF); reduce HFH or CV death. Mortality reduction demonstrated in HFrEF only. Eplerenone and finerenone are more receptor-specific and cause less gynaecomastia."
mraC=["Not tested at eGFR <25 mL/min/1.73 m²; use caution when K⁺ ≥5.0 mmol/L","If K⁺ >5.5 mEq/L: recheck, then consider dose reduction or temporary discontinuation; restart when hyperkalaemia resolves","Severe hyperkalaemia (K⁺ >5.5 or >6 mmol/L) → temporary down-titration/discontinuation of MRA and/or ACE-I/ARB/ARNI","Not recommended in pregnancy"]
d("eplerenone","Eplerenone",MRA+" (steroidal)","FMT","25 mg o.d.","50 mg o.d.",mraS,["Studied only in HFrEF (LVEF up to 35%)","Class I (B1) after MI with LVEF ≤40% and signs of HF or diabetes"],mraC,["mra","eplerenone"],"32, 36–37")
d("spironolactone","Spironolactone",MRA+" (steroidal)","FMT","12.5–25 mg o.d.","50 mg o.d.",mraS,["Optional 12.5 mg start where kidney status or hyperkalaemia warrant caution","Studied across LVEF ranges; TOPCAT overall neutral, but meta-analysis with FINEARTS-HF positive for LVEF >40%"],mraC,["mra"],"32, 36–37")
d("finerenone","Finerenone",MRA+" (non-steroidal)","FMT","10 mg (eGFR ≤60) / 20 mg (eGFR >60) o.d.","20 mg (eGFR ≤60) / 40 mg (eGFR >60) o.d.","Non-steroidal MRA studied in patients with LVEF >40% (FINEARTS-HF reduced HFH + CV death). Also recommended to reduce HF risk in T2DM with CKD (prevention).",["Start/target dose depends on eGFR (Table 11 footnote g)"],mraC,["finerenone","nsmra"],"32, 37","Dose pairing interpreted from Table 11 footnote g — verify against the PDF.")
SG="SGLT2 inhibitors"
sgS="Recommended in all symptomatic HF regardless of LVEF to reduce HFH or CV death; also improve QoL. CV mortality reduction only in HFrEF (in HFpEF benefit driven by fewer HFH). Initiate in hospital after stabilization in decompensated HF."
sgC=["Common side effects: genital and urinary tract infections","Mild initial eGFR decline expected; long-term kidney function improved"]
d("dapagliflozin","Dapagliflozin",SG,"FMT","10 mg o.d.","10 mg o.d.",sgS,[],sgC,["sglt2"],"32, 37")
d("empagliflozin","Empagliflozin",SG,"FMT","10 mg o.d.","10 mg o.d.",sgS,[],sgC,["sglt2"],"32, 37")
d("loop-diuretics","Loop diuretics","Diuretics","Symptomatic","—","—","Recommended to relieve congestion in HF with volume overload; dynamic, individualized dosing guided by volume status (Class I A). Use the lowest dose that maintains euvolaemia; needs fall with optimal FMT/GDIT. Effects on morbidity/mortality not studied in adequately powered RCTs.",["Best strategy: multiparameter assessment (clinical at rest and dynamic manoeuvres, eGFR, electrolytes, natriuretic peptides ± imaging)","In decompensated HF: IV loop diuretics for all patients with fluid overload (I A)","Add short-term IV acetazolamide or oral hydrochlorothiazide if fluid overload persists on loop diuretics (IIa B1)","Urinary Na⁺-guided diuretic therapy may be considered (IIb B1)"],["Electrolyte disturbances, neurohormonal activation, kidney function decline, symptomatic hypotension","Avoid chronic thiazide use in stable patients (severe, undetected electrolyte disturbances)"],["loop diuretic","diuretic","acetazolamide"],"32, 48–50")
d("k-binders","Potassium binders (patiromer, sodium zirconium cyclosilicate)","Other","—","—","—","Gastrointestinal K⁺ binders can treat/prevent hyperkalaemia and facilitate continuation/uptitration of ACE-I/ARNI/ARB and MRA. No specific recommendation in the guideline: clinical-outcome benefit unproven.",["REALIZE-K: signal towards more HF deterioration with sodium zirconium cyclosilicate vs placebo (not powered for outcomes)"],["GI symptoms; hypomagnesaemia (patiromer); oedema (sodium zirconium cyclosilicate)"],[],"32–33")
d("ivabradine","Ivabradine","If-channel inhibitor","AMT","5 mg b.i.d.","7.5 mg b.i.d.","Slows heart rate via If-current inhibition. Should be considered in symptomatic HFrEF, LVEF ≤35%, sinus rhythm, resting HR above 70 b.p.m., on highest tolerated FMT (IIa B1), or if beta-blocker not tolerated (IIa C). SHIFT: benefit driven mainly by fewer HFH.",["Initiate/uptitrate beta-blockers to target first, then reassess resting heart rate before adding ivabradine"],["Not recommended in pregnancy"],["ivabradine"],"34, 37–38")
d("vericiguat","Vericiguat","sGC stimulator","AMT","2.5 mg o.d.","10 mg o.d.","Oral soluble guanylate cyclase stimulator; may be considered in symptomatic HFrEF with LVEF <45% despite optimal FMT (IIb B1). VICTORIA (recent worsening HF): lower CV death/HFH, no reduction in death. VICTOR (stable ambulatory, LVEF ≤40%): neutral on primary endpoint.",["Less benefit seen at the highest NT-proBNP levels in VICTORIA"],[],["vericiguat"],"34, 37–38")
d("hydralazine-isdn","Hydralazine + isosorbide dinitrate","Vasodilators","AMT","37.5 mg/20 mg t.i.d.","75 mg/40 mg t.i.d.","Considered (IIa B2) in self-identified black patients with symptomatic HFrEF, LVEF ≤40%, on top of optimal FMT (reduced mortality and HFH, improved QoL in a small RCT). May be considered (IIb C) in HFrEF patients who cannot tolerate ACE-I, ARNI or ARB.",["Benefit in non-black patients unclear","Older evidence (V-HeFT, male patients on digoxin + diuretics) underpins the intolerance recommendation"],[],["hydralazine"],"34, 37–38")
d("digoxin","Digoxin","Cardiac glycosides","AMT","62.5 µg o.d.","250 µg o.d. (titrate to plasma level)","Should be considered in symptomatic HFrEF with LVEF ≤40% despite optimal FMT to reduce HFH (IIa B1). DIG: neutral on mortality, fewer HFH. Also IIa C for AF rate control when beta-blockers are insufficient or not tolerated.",["Target serum concentration <1.2 ng/mL","Eliminated mainly by the kidneys"],["Narrow therapeutic window — careful monitoring"],["digoxin","glycoside"],"34–35, 37")
d("digitoxin","Digitoxin","Cardiac glycosides","AMT","0.07 mg o.d.","0.1 mg o.d. (titrate to plasma level)","DIGIT-HF (HFrEF, NYHA III/IV or LVEF ≤30% NYHA II): composite of all-cause death or HFH 39.5% vs 44.1% (HR 0.82); neither death nor HFH alone significant. Considered with digoxin as a cardiac glycoside (IIa B1).",["Target serum 10.5–23.6 nmol/L in DIGIT-HF","Eliminated by hepatic metabolism"],["Narrow therapeutic window — careful monitoring"],["digitoxin","glycoside"],"34–35, 37")
d("omecamtiv","Omecamtiv mecarbil","Cardiac myosin activator","Not approved","—","—","GALACTIC-HF: modest reduction in HF events without a mortality benefit. Not currently approved for clinical use in HF.",[],[],[],"35")
d("iv-iron","Intravenous iron (iron deficiency)","Comorbidity therapy","Comorbidity","—","—","Recommended in symptomatic HFrEF with iron deficiency to alleviate symptoms and improve QoL (I B1); should be considered to reduce HFH (IIa B1).",["Iron status (TSAT, ferritin) is part of the initial laboratory work-up"],[],["iron"],"66–67")
d("glp1-tirzepatide","Semaglutide / tirzepatide","Incretin-based therapy","Comorbidity","—","—","Should be considered in symptomatic HF with LVEF ≥45% and BMI ≥30 kg/m², regardless of diabetes status, to reduce weight and improve exercise capacity and QoL (IIa B1). Prevention: GLP-1 RA in T2DM with another CV risk factor (IIa A).",[],[],["semaglutide","glp-1"],"34–35, 65")
d("anticoag","Oral anticoagulants (DOACs, VKAs)","Antithrombotics","Comorbidity","—","—","Oral anticoagulation is recommended in HF with clinical AF at elevated thromboembolic risk by CHA₂DS₂-VA (I A); DOACs preferred over VKAs (I B1). Patients with HCM and cardiac amyloidosis need anticoagulation irrespective of score.",[],[],["anticoag","doac"],"58–60")
d("af-rate","AF rate/rhythm drugs (beta-blockers, digoxin, amiodarone)","Antiarrhythmics","Comorbidity","—","—","HFrEF with AF: beta-blockers first-line for rate control (I C); digoxin if rate remains high or beta-blockers not tolerated (IIa C); IV amiodarone or digoxin for acute rate control in haemodynamically unstable patients (IIb C). Urgent cardioversion if rapid rates with haemodynamic instability (I C).",[],[],["amiodarone","rate control"],"59–60")
d("acute-agents","Acute decompensated HF agents (oxygen, vasodilators, inotropes, vasopressors, opiates)","Acute care","Acute","—","—","Oxygen if SpO₂ <90% or PaO₂ <60 mmHg (I C). IV vasodilators may be considered if SBP >110 mmHg (IIb C). Inotropes may be considered if SBP <90 mmHg with hypoperfusion unresponsive to standard treatment (IIb C). Vasopressors, preferably norepinephrine, in cardiogenic shock (IIb C). Routine opiates not recommended (III C).",[],[],["vasodilator","inotropic","vasopressor","opiate","oxygen"],"48–51")
d("ttr","TTR-directed therapy (vutrisiran, tafamidis, acoramidis)","Amyloidosis","Disease-specific","—","—","TTR silencer (vutrisiran) or stabilizer (tafamidis or acoramidis) is recommended in variant or wild-type ATTR cardiac amyloidosis, NYHA I–III, to reduce symptom progression, CV hospitalization and death (I A).",[],[],["ttr","amyloid"],"75–77")
d("avoid","Drugs to avoid or use with caution (NSAIDs/COX-2, pregnancy)","Avoid","Safety","—","—","NSAIDs and COX-2 inhibitors are not recommended (III B2) — they worsen HF and increase HFH. In pregnancy, ACE-I, ARB, ARNI, MRA, ivabradine and SGLT2-I are not recommended (foetotoxicity/teratogenicity); non-selective beta-blockers should be switched to β1-selective agents (metoprolol, bisoprolol). Glucose-lowering drugs without proven HF safety should be avoided in prevention.",[],[],["nsaid","pregnan"],"64, 69, 74")
json.dump(D,open('build/data/drugs.json','w'),ensure_ascii=False)
print(len(D))
